version: "3.7"
services:
  eventhos-web:
    build:
      context: ./eventhos-web
      dockerfile: Dockerfile
    container_name: eventhos-web
    ports:
      - "2110:2110"
    environment:
      URL: http://localhost:2109
    depends_on:
      eventhos-api:
        condition: service_healthy
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  eventhos-api:
    build:
      context: ./eventhos-api
      dockerfile: Dockerfile
    container_name: eventhos-api
    ports:
      - "2109:2109"
    environment:
      DATA_BASE_NAME: "eventhos"
      DATA_BASE_HOST: host.docker.internal
      DATA_BASE_PORT: 3306
      DATA_BASE_USER: "usr_eventhos"
      DATA_BASE_PASSWORD: "abcdefg"
      NODE_ENV: "production"
      CPU_COUNT: 3
      PORT: 2109
      JWT_SECRET: "secret"
      CRYPTO_KEY: "secret_key"
      DATA_BASE_ACQUIRE_CONNECTION_TIMEOUT: 10000
      DATA_BASE_POOL_MAX: 300
      DATA_BASE_POOL_MIN: 100
    healthcheck:
      test: curl --fail http://localhost:2109 || exit 1
      interval: 10s
      retries: 100
      start_period: 20s
      timeout: 10s
    depends_on:
      eventhos-db:
        condition: service_healthy
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 1024M
  eventhos-db:
    image: mysql:5.7
    command: mysqld --sql_mode="" --max_connections=1100 --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    container_name: eventhos-db
    ports:
      - "3306:3306"
    volumes:
      - ./eventhos-api/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "abcdefg"
      MYSQL_PASSWORD: "abcdefg"
      MYSQL_USER: "usr_eventhos"
      MYSQL_DATABASE: "eventhos"
      TZ: America/Lima
    deploy:
      resources:
        limits:
          memory: 1024M
    healthcheck:
      test: 'cat /var/log/mysql/general-log.log | grep "root@localhost on  using Socket"'
      interval: 1s
      retries: 120
networks:
  app_network:
    driver: bridge
