version: "3.7"
services:
  eventhos-db:
    image: mysql:5.7
    command: mysqld --sql_mode="" --max_connections=1100 --general-log=1 --general-log-file=/tmp/mysql-general-log.log
    container_name: eventhos-db
    ports:
      - "3306:3306"
    volumes:
      - ./eventhos-api/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_USER: "usr_eventhos"
      MYSQL_DATABASE: "eventhos"
      TZ: America/Lima
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: 'cat /tmp/mysql-general-log.log | grep "root@localhost on  using Socket"'
      interval: 10s
      retries: 120
  eventhos-api:
    build:
      context: ./eventhos-api
      dockerfile: Dockerfile
    container_name: eventhos-api
    ports:
      - "${EVENTHOS_API_PORT:-2109}:2109"
    environment:
      NODE_ENV: "production"
      CPU_COUNT: 1
      PORT: 2109      
      DATA_BASE_NAME: "eventhos"
      DATA_BASE_HOST: host.docker.internal
      DATA_BASE_PORT: 3306
      DATA_BASE_USER: "usr_eventhos"
      DATA_BASE_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      DATA_BASE_POOL_MAX: 300
      DATA_BASE_POOL_MIN: 100
      DATA_BASE_ACQUIRE_CONNECTION_TIMEOUT: 10000
      JWT_SECRET: ${JWT_SECRET:-changeme}
      CRYPTO_KEY: ${CRYPTO_KEY:-changeme}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_TLS_CIPHERS: SSLv3
      SMTP_DEFAULT_RECIPIENT: ${SMTP_DEFAULT_RECIPIENT}
      TZ: America/Lima
    healthcheck:
      test: curl --fail http://localhost:2109 || exit 1
      interval: 10s
      retries: 100
      start_period: 20s
      timeout: 10s
    depends_on:
      eventhos-db:
        condition: service_healthy
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 512M
  eventhos-web:
    build:
      context: ./eventhos-web
      dockerfile: Dockerfile
    container_name: eventhos-web
    ports:
      - "${EVENTHOS_WEB_PORT:-2110}:2110"
    environment:
      EVENTHOS_API_BASE_URL: "${EVENTHOS_API_BASE_URL:-http://localhost:2109}"
      TZ: America/Lima
    depends_on:
      eventhos-api:
        condition: service_healthy
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 128M
  mock-api:
    build:
      context: ./mock-api
      dockerfile: Dockerfile
    container_name: mock-api
    ports:
      - "9000:9000"
    environment:
      PORT: "9000"
    depends_on:
      eventhos-api:
        condition: service_healthy
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 128M          

networks:
  app_network:
    driver: bridge
